#!/bin/bash

# Launch or focus on a given TUI identified by the passed in as the command.
# Use by commands like omarchy-launch-wifi to ensure there is only one wifi configuration screen open.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APP_ID="org.omarchy.$(basename "$1")"
LAUNCH_COMMAND="$SCRIPT_DIR/hdk-launch-tui $@"

exec "$SCRIPT_DIR/hdk-launch-or-focus" "$APP_ID" "$LAUNCH_COMMAND"
